/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import lib.dbConnect;

/**
 *
 * @author Dau
 */
public class panSetting extends javax.swing.JPanel {
    Connection con = null;
    Statement st = null;
    ResultSet rs = null;
    /**
     * Creates new form panSetting
     */
    public panSetting() throws SQLException {
        initComponents();
        //this.setVisible(true);
        try {
            con = dbConnect.create();
            st = con.createStatement();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(panSetting.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void resetForm() {
        pwOld.setText("");
        pwNew.setText("");
        pwRenew.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        pwOld = new javax.swing.JPasswordField();
        pwNew = new javax.swing.JPasswordField();
        pwRenew = new javax.swing.JPasswordField();
        pwReport = new javax.swing.JLabel();

        jLabel1.setText("old password");

        jLabel2.setText("new password");

        jLabel3.setText("re-enter new password");

        jButton1.setText("change");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pwReport, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                    .addComponent(jButton1)
                    .addComponent(pwOld, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                    .addComponent(pwNew)
                    .addComponent(pwRenew))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(pwReport)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(pwOld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(pwNew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(pwRenew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(40, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
            String pOld = new String(pwOld.getPassword());
            String pNew = new String(pwNew.getPassword());
            String pRenew = new String(pwRenew.getPassword());
            
            //get raw password
            String q = "SELECT password FROM admins WHERE userid = 1";
            rs = st.executeQuery(q);
            String pRaw = null;
            while(rs.next()) {
                pRaw = rs.getString("password");
            }       
            System.out.println(pRaw);
            if (pOld.equals(pRaw)) {                
                if (pNew.equals(pRenew)) {
                    String qN = "UPDATE admins SET password = '"+pNew+"'";
                    int rowAffected = st.executeUpdate(qN);
                    if (rowAffected >0) {
                        pwReport.setText("change password successfully!"); 
                        resetForm();
                    }
                    else {
                        pwReport.setText("Has something error!");
                    }
                } else {
                    pwReport.setText("new password not match!");
                }
            } else {
                pwReport.setText("old password wrong!");
            }
        } catch (SQLException ex) {
            Logger.getLogger(panSetting.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField pwNew;
    private javax.swing.JPasswordField pwOld;
    private javax.swing.JPasswordField pwRenew;
    private javax.swing.JLabel pwReport;
    // End of variables declaration//GEN-END:variables
}
